spark.driver.extraClassPath    /opt/spark/jars/sqlite-jdbc-3.46.0.0.jar:/opt/spark/jars/clickhouse-jdbc-0.6.3-all.jar
spark.executor.extraClassPath  /opt/spark/jars/sqlite-jdbc-3.46.0.0.jar:/opt/spark/jars/clickhouse-jdbc-0.6.3-all.jar

spark.authenticate             false
spark.ssl.enabled              false
spark.network.crypto.enabled   false
spark.ui.https.enabled         false
